### ISSUE TITLE
Line 6 in PWMs

### ISSUE THREAD

**Issue by saskra** [GfellerLab/MixMHCpred#2]
What is the meaning of the numbers in line six in the PWM files, e.g. "1.00000	2066	1" in "lib/pwm/class1_9/A0101_1.txt"? And are these numbers relevant for the software if I want to use my own PWMs?

**Comment by dagfeller** [comment]
Sorry for my late reply, I'm not checking often the issues.
The first element gives the weight of the PWM (most of the time equal to one, since most alleles only have one PWM), the second the number of peptides used to build this PWM, and the last one the origin of the ligands (1: Curated MS data; 2: MS data from IEDB; 3: Binding affinity data from IEDB). Only the first element is used in MixMHCpred.
