### ISSUE TITLE
Empty Output

### ISSUE THREAD

**Issue by Famke-Monstrey** [GfellerLab/MixMHCpred#8]
Hello, I tried to run MixMHCpred-2.2 using linux but my output is empty. I tried using a simple list of only peptides, as well as the list with header but it still doesn't work. 
[test.txt](https://github.com/GfellerLab/MixMHCpred/files/11250112/test.txt)

**Comment by dagfeller** [comment]
Did you recompute the C++ code?

**Comment by Famke-Monstrey** [comment]
That was indeed a problem! Thank you! 
However, now i get the error: Unable to open file: test.txt/PerRank/A0201.txt
With test.txt being my input file with a peptide list

**Comment by dagfeller** [comment]
I think it may be because you have the wrong path in the MixMHCpred executable file. You need to manually give the path to the lib/ folder (i.e., /PATH_TO_MIXMHCPRED/lib). Also, you should always avoid having spaces or other weird character in any path or any filename, as this can confuse lots of different scripts. Let me know if this solves the issue

**Comment by Famke-Monstrey** [comment]
Thank you for the help, it works fine now! :)
